### PR TITLE
Updated 512 / 712 Instructions

### PR DESCRIPTION
**Pull request by eliotsdad**
Step by step instructions to create the necessary .json files for the 512, and added code inline for those files.

### CODE REVIEW

**Comment by danamlewis** [comment]
Thanks, @eliotsdad! Just added some formatting changes. Will see if @elute or someone can give this a try before we merge in.

**Comment by danamlewis** [comment]
One more note: wondering if we should provide guidance on which of the things in the settings file that need adjusting, vs. can be left at the default. Can someone who tests this PR provide a list of which you needed to edit?

**Comment by ChrisWeinman** [comment]
Yep, I'll run through it and take some notes.

**Comment by scottleibrand** [comment]
This PR answers the questions @redshif83 was answering in Gitter this morning.  It looks like an improvement over the previous docs and IMO should be merged.  Further edits can always be made as additional PRs.

**Comment by danamlewis** [comment]
Going ahead and merging to master, then @Kdisimone is opening a new PR with some edits. Thx everyone for helping with the x12s.

**Pull request merged**
