### PR TITLE
openaps install no longer in Phase 0

### PR DESCRIPTION
**Pull request by tghoward**
Ak!  the link I've deleted here is dead. And I can't find the instructions anywhere. Can detailed instructions for openaps installation be recovered?

### CODE REVIEW

**Comment by danamlewis** [comment]
I deleted that since it was referenced in the setup script page. Your fix looks good to me, or are you saying there's still something needed from that old page that is missing?

**Comment by danamlewis** [comment]
(Here is where I deleted it: https://github.com/openaps/docs/pull/428/commits/256e2205bf8400849705e8b87e135c652680de67)

**Comment by tghoward** [comment]
No, I guess my fix can stand. This is now the very first introduction to openaps though, right?   I'll crib a little more text from what you deleted and add it in here.

**Comment by danamlewis** [comment]
Correct. Thanks!

**Comment by tghoward** [comment]
@danamlewis  Ok, added a few more lines, see what you think. Tim

**Comment by tghoward** [comment]
Great!

**Comment by danamlewis** [comment]
Formatting tweaks in this commit: https://github.com/openaps/docs/commit/3c6af93d29adf22fc2ddeb4c4650537253b8dc8b

**Pull request merged**
