### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danamlewis**
More README additions, (similar to #31 on openaps-js). @channemann @scottleibrand etc.

### CODE REVIEW

**Comment by bewest** [comment]
What do you think about the meta-colophon bit about this book being written in markdown.  Seems like we can remove that or move it to colophon section?

**Comment by bewest** [comment]
This might serve as nice basis for exploring common snippets to include in all the project READMEs, nice.

**Comment by danamlewis** [comment]
Hmm, maybe remove it? It looks a bit weird in github, but could go either way.

**Comment by channemann** [comment]
The initial addition of that weird "written in markdown" section was because the same page was going to show up as the readme in GitHub and the intro page in the GitBook version, and I wasn't quite clear on what the link would end up being (it was my first PR with a GitBook). I'd go ahead and remove it.

If this is going to go into all of the openaps- repo readme files, is it worth cross-linking them (i.e. having an index of sorts)? Then you could label them each as _monitor_, _predict_, and _control_ in that index.

I would also look to put a little more stress on the cover-our-ass portion. Not sure what the actual language should be (isn't Ed a lawyer?), but some emphasis on that line might be appropriate.

**Comment by danamlewis** [comment]
Closing since @channemann's #9 pulls my additions in to his big PR there.

**Pull request closed without merging**
