### PR TITLE
Use new software-properties-common package

### PR DESCRIPTION
**Pull request by cascer1**
python-software-properties has been replaced

### CODE REVIEW

**Comment by cascer1** [comment]
I haven't checked installing with the package removed entirely, but it does fail completely without it because apt-get can't find the package and kicks the bucket

**Comment by scottleibrand** [comment]
Ok.  I'd have a slight preference for removing it if it's no longer needed, if you want to check that.  I probably won't want to go reimage a rig just to check that, though, so I'm good with your solution as-is if you'd rather leave it.

**Comment by cascer1** [comment]
I'll check if it works without it entirely later, my current setup will probably be reset soon anyway.

**Comment by jbwittmer** [comment]
I manually installed the new package and got a rig working from scratch but didn't try going without it entirely.  So I can confirm replacing python-software-properties with software-properties-common works but I don't know about leaving it out entirely.

**Pull request merged**
