### PR TITLE
FIX - Interrupting kernel messages in console/screen mode

### PR DESCRIPTION
**Pull request by MelissaParkey**
How to fix the interrupting kernel messages in console/screen mode for OpenAPS (kernel messages are those lines that start with a set of bracketed numbers usually)
You can fix the interrupting messages for an individual console session using the command: dmesg -D
Or, if you want a more permanent solution (see screenshot), you will add a line to a file. This will keep the messages from appearing for every screen/console connection for that rig. You can add the line by going using the command: vi /etc/rc.local
The line you are going to add is: sudo dmesg -n 1
Remember to save and exit the vi editor by using esc and then :wq

(Thank you Katie DiSimone for creating this awesome solution to an aggravating issue.)

interrupting kernel messages
fix interrupting kernel messages

### CODE REVIEW

**Comment by danamlewis** [comment]
thanks @MelissaParkey ! Can you try re-targeting this to the master branch? Click on edit, and then where it says new-docs, try to select master?

**Comment by MelissaParkey** [comment]
So I read this after the other email. And of course my ignorance is still present 😳
When I get to my computer I will try though!!

Melissa

**Comment by danamlewis** [comment]
@MelissaParkey have you given a try to retarget this to master?

**Comment by MelissaParkey** [comment]
I'm going to look at it right now. 😜. If I can't figure it out can you/will you teach me!?

Melissa

**Comment by danamlewis** [comment]
Ok - figured out what was going on :D. @MelissaParkey - I think you want to go to this page (http://openaps.readthedocs.io/en/latest/docs/walkthrough/phase-0/setup-edison.html), then follow the PR instructions (http://openaps.readthedocs.io/en/latest/docs/Resources/my-first-pr.html) for editing that page. I'd suggest adding it to the very bottom of that page.  You can include it in this PR, or no worries if you end up creating a new PR . You'll want to take the content from your note in the top of this PR and actually put it on the page. (I can help with images and formatting, but want you to give it a stab in making the edits!)

**Comment by danamlewis** [comment]
(closing in favor of the other PR that had the changes in it :) )

**Pull request closed without merging**
