### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by logichammer**
RIght direction?

### CODE REVIEW

**Comment by logichammer** [comment]
asdf

**Comment by danamlewis** [comment]
@logichammer looks like you hadn't re-pulled dev in recent history (i.e. since January) before submitting the PR here. I would re-pull dev, because we made some HUGE changes in February in terms of structure and content, and I think it might have pulled in a lot of this information already from the previous PR you had. So going to close this PR with the recommendation to re-open (or start a new PR) after you freshly pull the current openaps/dev back to your end and see what should be added from there.

**Comment by logichammer** [comment]
Perfect...I actually deleted my fork and started over since it was all SO
old.  I have the freshest version of dev and should be making a dent in the
documentation this week.

**Comment by danamlewis** [comment]
Thx @logichammer !

**Pull request closed without merging**
