### PR TITLE
Wip/ama docs to master

### PR DESCRIPTION
**Pull request by danamlewis**
Creating the PR to ask someone to review and compare what from wip/ama-docs needs to be moved over to master.

### CODE REVIEW

**Comment by tomasboudr** [comment]
looks good to me.

**Comment by danamlewis** [comment]
I was reminded we were waiting until AMA branch of code is merged to dev, which needs to happen before we merge the docs...so waiting for that.

**Comment by danamlewis** [comment]
Re-poking this one open now that AMA is part of dev branch of oref0. 

Known to be needed to add before merging: make sure it's clear that it's dev branch of oref0 (currently reads as grab AMA branch). May also want to add notes about how to adjust or limit the auto-sensitivity parameters (per notes from @eyim and @jasoncalabrese , they may want to do this one) and also add in how to enable temp targets, because I think that's also missing from the docs.

**Comment by eyim** [comment]
Okay - made the changes and sent the pull request

**Comment by scottleibrand** [comment]
Any reason not to merge this now?

**Comment by jasoncalabrese** [comment]
Should we do something with bolus snooze?  Maybe a new preference?

**Comment by jasoncalabrese** [comment]
Oh, this is docs, I thought it was oref0, nevermind.

**Comment by danamlewis** [comment]
Is there anything from wip/ama-docs that needs pulling in to the master or dev docs?

**Comment by danamlewis** [comment]
Actually, I vote for closing. I pulled the key bits in about AMA and auto-sens. See https://github.com/openaps/docs/commit/c3c2734c83151fa428fd0845825b5aab817f7503. Let me know if anyone else sees anything missing, otherwise will close this PR.

**Comment by scottleibrand** [comment]
Should we delete the wip/ama-docs branch, or is there anything there we want to save still?

**Comment by danamlewis** [comment]
I closed this PR a month and a half ago, and haven't heard that we're missing anything, so I would be fine to delete at this point.

**Pull request closed without merging**
