### PR TITLE
Changing Logs files to Log files 

### PR DESCRIPTION
**Pull request by JaysonEwer**
(YAY for Jayson's first PR)  :-D

### CODE REVIEW

**Comment by scottleibrand** [comment]
:+1:

**Comment by danamlewis** [comment]
Kudos @JaysonEwer ! Can you retarget this to dev now? I just merged 114, so dev is now the place to be targeting.

**Comment by JaysonEwer** [comment]
Sweet, will do, I'll take care of that tonight.  

Thank you, Dana!

**Comment by JaysonEwer** [comment]
I've retargeted to dev, have a good night.

Thanks,

Jayson

**Pull request closed without merging**
