### PR TITLE
Improvement for docs for token based authentication

### PR DESCRIPTION
**Pull request by PieterGit**
requires https://github.com/openaps/oref0/pull/470 to be merged to dev

### CODE REVIEW

**Comment by PieterGit** [comment]
Ready for merging. Thanks @ceben80 and @betluis for testing it out

**Comment by PieterGit** [comment]
I was about to update the docs with @scottleibrand decision not to make token based authentication the default in the 0.5.0 release (see discussion on i-to-b [here](https://gitter.im/nightscout/intend-to-bolus?at=595bb298329651f46e51b0be), [here](https://gitter.im/nightscout/intend-to-bolus?at=595bd501703e565c3373a817) and [here](https://gitter.im/nightscout/intend-to-bolus?at=595bf1c0c101bc4e3a4fd56d). 

Thanks for fixing that and my grammar. I'm not a native speaker. 

Let's try to give it more exposure and I'm happy to fix possible errors in the authentication stuff if they occur.

**Comment by scottleibrand** [comment]
No worries, thanks for all your work on this.  I think these docs updates are ready to merge unless @danamlewis or @Kdisimone need to refactor anything for their new-docs work.

**Comment by PieterGit** [comment]
@danamlewis : can you merge this?

**Comment by scottleibrand** [comment]
Merged via https://github.com/openaps/docs/pull/940

**Pull request closed without merging**
