### PR TITLE
Update overview.md moved and modified

### PR DESCRIPTION
**Pull request by julieraines**
Suggesting moving the OVERVIEW so that it happens before INSTALL and then CREATE FIRST WORKSPACE

### CODE REVIEW

**Comment by scottleibrand** [comment]
Want to PR these to dev instead of to master, and then we can merge to master once all the moves are complete?

**Comment by julieraines** [comment]
question - is there an easy way to copy without redoing? go to commits and hit that little copy button off to the right maybe?  or do I just redo?

**Comment by scottleibrand** [comment]
You already have the commits all staged in a branch called julieraines:patch-1.  You just need to PR from that branch to dev instead of to master.  You can do so at https://github.com/openaps/docs/compare/dev...julieraines:patch-1 (which I got by going to https://github.com/julieraines/docs, hitting New Pull Request, and changing the branches in the drop-downs)

**Comment by scottleibrand** [comment]
Already merge to dev.  Closing the PR to master.

**Pull request closed without merging**
