### PR TITLE
Fixed table layout

### PR DESCRIPTION
**Pull request by inventor96**
The table was not displaying due to missing start and end pipes.

### CODE REVIEW

**Comment by trevettallen** [comment]
Hey, what's this? 😀🤔

**Comment by scottleibrand** [comment]
It's a pull request for fixing a table in the OpenAPS docs. 😛

**Comment by scottleibrand** [comment]
@inventor96 GitHub thinks your change is a no-op: it's probably less strict. What were you viewing it in that required the `|` at the start and end? Do you have / can you make screenshots of the before and after?

**Comment by inventor96** [comment]
The layout at <https://openaps.readthedocs.io/en/latest/docs/Gear%20Up/edison.html#soldering> isn't great:

image

I'm hoping that the pipes will fix it. I didn't see any examples on how to test this locally, so I can't confirm this will actually do it, but I've seen several other Markdown renderers that use the start and end pipes.

**Comment by inventor96** [comment]
Alternatively, we could just remove the Markdown table and use the picture of the table that's already there, but I'm always in favor of using plain text to help with search/indexing.

**Review by scottleibrand — APPROVED** [review]
Worth a try

**Pull request merged**
