### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by dm61**
I've made some updates to the visualization section based on my recent experience. I think someone else should take a look at it, especially the "Configuring and Uploading OpenAPS Status" subsection - I have not been able to figure out how to add ns-upload as an openaps device that would produce the desired entries in the openaps.ini file. Included is my best attempt. There are other details I am not so sure about - the treatment upload subsection is largely based on copy and paste from Scott's script and I do not think I fully understand all details.

### CODE REVIEW

**Comment by TC2013** [comment]
Line 63 should read: 
openaps report add monitor/upload-status.json JSON ns-status shell monitor/clock-zoned.json monitor/iob.json enact/suggested.json enact/enacted.json monitor/battery.json monitor/reservoir.json monitor/status.json

ns-status and shell are turned around

**Comment by jasoncalabrese** [comment]
Would be great to add some info about the new pump plugin here, it's in the NS dev [readme](https://github.com/nightscout/cgm-remote-monitor/blob/dev/README.md#built-inexample-plugins) now

screen shot 2016-01-27 at 8 33 25 am

**Comment by dm61** [comment]
I've added a brief description of the new pump plugin, with an example of how to add reservoir and battery, and with a link to the NS readme. The pump plugin is very useful - thanks!

**Comment by scottleibrand** [comment]
:+1: I think this is better than what we have now, and ready to merge.  @jasoncalabrese can you PR your suggested changes to dev after that?

**Comment by danamlewis** [comment]
@dm61 thanks for the further additions and great work on this. Think we'll go ahead and merge to dev, and then try to figure out what is still tripping people up, but this is way better than current dev regardless :)

**Pull request merged**
