### PR TITLE
Add myself to loops in progress

### PR DESCRIPTION
**Pull request by tatigger**

### CODE REVIEW

**Comment by tatigger** [comment]
Add myself to open loops in progress

**Comment by scottleibrand** [comment]
Did you change your mind?  Or can I go ahead and merge this?

**Comment by tatigger** [comment]
Go ahead and merge it. I was looking for ways to make it harder, lol 

Terri - Sent from my iPhone

**Comment by scottleibrand** [comment]
LOL, found one! ;-)

**Pull request merged**
