### PR TITLE
Add Smartphone Assistant Shortcuts to Customize-Iterate

### PR DESCRIPTION
**Pull request by BergFulton**
Add instructions on how to add Smartphone Assistant shortcuts that integrate with NS. Added a known shortcut link.

### CODE REVIEW

**Comment by danamlewis** [comment]
Nice! thanks for this, @BergFulton. How would you feel about moving it over to this page (which we should re-title as IFTTT/Smartphone/SmartWatch integrations anyway?) https://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/ifttt-integration.html

**Comment by danamlewis** [comment]
and by that I mean - you can move it, or I can move it over for you since you've done the hard work writing it! just wanted to check on that before I move it.

**Comment by BergFulton** [comment]
@danamlewis Yep, I think that makes sense to move it to the IFTTT page. I'll take care of it.

**Comment by danamlewis** [comment]
Hmm, this looks like the content got deleted, but not re-added?

**Comment by danamlewis** [comment]
Closing as no content changes left in this branch; but also hoping https://github.com/openaps/docs/pull/1414 achieves the same goal (please edit/add there if you have more content to add!)

**Pull request closed without merging**
