### PR TITLE
Update Pump-rig-communications-troubleshooting.md

### PR DESCRIPTION
**Pull request by old-square-eyes**
:: Added space to 4 occurrences of `killall-g`
:: Improve mmtune results explanation

### CODE REVIEW

**Comment by scottleibrand** [comment]
Please open a new PR without the killall-g changes. That’s the name of the script that properly kills bash scripts like killall -g does.

**Comment by old-square-eyes** [comment]
@scott I may be guilty of making assumptions. Sorry, I'm just learning.

I did see it has a space for the argument earlier in the command. 

Also when I run it as is, I get... 

```cd ~/myopenaps && sudo service cron stop && killall -g openaps ; killall-g oref0-pump-loop; OREF0_DEBUG=1 oref0-mmtune && sudo service cron start
openaps: no process found
-bash: killall-g: command not found
mmtune: 2019/11/20 06:57:01 connected to CC111x radio on /dev/spidev5.1... ```

**Comment by scottleibrand** [comment]
Are you running an up to date 0.7.0 install? We can use killall -g for the old 0.6.3 commands but have to use the killall-g wrapper script to kill the 0.7.0 bash loop scripts.

**Comment by old-square-eyes** [comment]
This rig is 0.7.0 Dev, about 10 commits behind the new 0.7.0 Master

**Comment by scottleibrand** [comment]
https://github.com/openaps/oref0/pull/1306

**Pull request closed without merging**
