### PR TITLE
Added Name - Mike Wright

### PR DESCRIPTION
**Pull request by mwright408**
Added Name - Mike wright

### CODE REVIEW

**Comment by scottleibrand** [comment]
Heh, that was fast. ;-)

**Comment by mwright408** [comment]
Ha! Thanks. I am new new to all this. Your tutorial has been an amazing help.

**Comment by scottleibrand** [comment]
Hop on over to gitter and we might have an even easier one for you to follow...  ;-)

**Comment by mwright408** [comment]
How so? Could you give a specific link? I could us all the help I could get...

**Comment by scottleibrand** [comment]
https://gitter.im/nightscout/intend-to-bolus

**Comment by mwright408** [comment]
Thanks again!

**Comment by mwright408** [comment]
Sorry, one more question:
I'm trying to "Create a new instance of openaps in a new directory"

But I keep getting the message "No script named 'openaps'

Any ideas? I'm stuck at this point

**Pull request merged**
