### PR TITLE
Hardware updates I made

### PR DESCRIPTION
**Pull request by SirBinky**
Sorry about the 3 commits, I didn't realise github was saving each edit i did. I copied the description worried I'd lost it. 

I'm hoping these changes make it a bit clearer and I updated the hardware to Raspberry Pi 3. 

I wasn't sure about keeping the Rpi2 stuff in but I thought for simplicity to remove it.

### CODE REVIEW

**Comment by scottleibrand** [comment]
Not sure whether or not we want to recommend the Pi 3 by default. It has much higher power consumption, which is problematic for some people who want to use it for a mobile rig. Let's open this PR up for comments.

**Comment by xpucuto** [comment]
If you add the PI3 in the docs , you have to know that the Tecknet battery can not charge trough when the PI3 is connected . This is the reason i bought the Zendure battery which works great.

**Comment by loudestnoise** [comment]
My RPi rig is an RPi3. I use the [MoKo 9000mAh battery](https://amzn.com/B00FGN1OBU) and I get easily 12 to 14 hours of run time without losing power to the RPi. I would recommend changing the recommendation to the RPi3 because of the added benefit of built in WiFi/Bluetooth.

**Comment by shgrady** [comment]
I think it might have been helpful to mention the trade-off. I bought a lot of the wrong stuff in the beginning, like a wifi dongle you don't need with 3 (which could be corrected at line 115 if you keep both), since 2 and 3 at the same price point, 3 "seemed" like a good idea. Can we keep both and explain the difference in power consumption, because by using the 3, neither a UPS set up, or one of the powerbanks I bought worked. Long way from rig number 2, but definitely going back to a Pi2 for it when I do. Even though the Tecknet appears to not be charging through, the minute you disconnect the Pi, it jumps to all 5 LEDs.

**Comment by Spazholio** [comment]
I'd recommend removing any explicit references to Pi2 or Pi3, but have a comparison page that outlines the pros/cons of each.  If the code runs identically on each one (which I believe it does) then I think advocating one over the other will just lead to, "The docs say Pi3, but I only have a Pi2 - will this work on mine?" type questions.

**Comment by C-Ville** [comment]
I think it really depends on the setup you want to use. The pi 3 is nice for BT and WiFi. If you want to use an ERF module or TI over serial, than you will not have BT on the pi3 as far as I know. Therefore the benefit of a pi3 is not that great for such a setup. As for reference design I think the pi3 is great.

**Comment by SirBinky** [comment]
I've rewritten the file based on the comments above. Adding back the Pi 2 data and changing Rpi to neutral versions outside the specific mentions. Also i've added the plus and minus points for each model.

**Comment by danamlewis** [comment]
I like this with the revised changes, 👍 if someone fixes the merge conflicts.

**Comment by SirBinky** [comment]
Sorry what do you mean merge the conflicts? I thought the newest doc was good to merge?

**Comment by loudestnoise** [comment]
Yeah, I'm with @SirBinky on this. What merge conflicts are there? I mean I see the Github message saying there are, but if you click on Files Changed and it's just Paul's text vs Master. Or is the conflict also talking about other branches? For example, I've updated this page from my forked master branch, but I was under the impression we were supposed to be PR into the dev branch for review and then those with write access would then merge into master.

**Comment by SirBinky** [comment]
I thought we forked the dev and pr'd the master?

**Comment by danamlewis** [comment]
It says "this branch has conflicts that must be resolved", so there's another PR that got pulled in that made changes that conflict with whatever's in this one. So someone has to look in the command line and compare to see which changes conflict. The content from here has a thumbs up to get merged in, it's likely a matter of a small change in the old one or this one but it has to be done from the command line. 

Historically, you were supposed to fork dev and PR into dev, then we'd move dev to master, but we're allowing PRs to master now. So fork master and PR to master moving forward, unless you have huge gargantuan changes, in which case I'd maybe target to dev still so we can work through those.

**Comment by loudestnoise** [comment]
Yeah, I just read #189 and I see that's the new procedure. I like it!

**Pull request merged**
