### PR TITLE
Adding the priority designation to wifi networks

### PR DESCRIPTION
**Pull request by Kdisimone**

### CODE REVIEW

**Comment by scottleibrand** [comment]
https://en.m.wikipedia.org/wiki/Cargo_cult :-)

**Comment by Kdisimone** [comment]
https://communities.intel.com/thread/110485

FYI: Here's the google thread that led me to suspecting priority may solve our issue.  I didn't try the original poster's suggestion of deleting second line.

**Comment by scottleibrand** [comment]
Maybe the next step would be to capture a repro of the issue?: a wpa_supplicant.conf that causes the problem and another that resolves it.

**Comment by Kdisimone** [comment]
And this issue came up on two rigs in one household. One rig was freshly made using bootstrap on a preflashed edison from hamshield (not 0.2.0). The other rig was created the old way (by myself jubilinux 0.1.1 like the other rig).  Both rigs weren't working. 

I reflashed rig one. Did non-bootstrap wifi setup, problem persisted. Set priorities and wlan0 worked finally. 

Went to second rig, confirmed it was giving same error message as the first rig was. Didn't reflash, didn't redo loop installation.  Simply added priorities and wlan0 started again, rig worked immediately again. 

Just for further info

**Comment by Kdisimone** [comment]
Want me to post the interfaces and wpa_supplicants for them?

**Comment by scottleibrand** [comment]
Sure. Please redact the passwords if they're sensitive.

**Comment by Kdisimone** [comment]
This version works...

```
root@devon1:~# cat-wifi
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
network={
    ssid="308 Burt Street"
    psk="xxxx"
    priority=1
}
network={
    ssid="Newell Broadcasting"
    psk="xxxx"
    priority=2
}
network={
    ssid="Solberg"
    psk="xxxx"
    priority=3
}
network={
    ssid="TP-Link_D6EA_5G"
    psk="xxxx"
    priority=4
}
network={
    ssid="Baker Wireless Network WiFi"
    psk="xxxx"
    priority=5
}
network={
    ssid="Rig2"
    psk="xxxx"
    priority=6
}
```

**Comment by Kdisimone** [comment]
This version does not work:

**Comment by Kdisimone** [comment]
This version also works (but obviously only for the one network):

root@devon1:~# cat-wifi
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
network={
    ssid="308 Burt Street"
    psk="xxxx"
}
#network={
#    ssid="Newell Broadcasting"
#    psk="xxxx"
#}
#network={
#    ssid="Solberg"
#    psk="xxxx"
#}
#network={
#    ssid="TP-Link_D6EA_5G"
#    psk="xxxx"
#}
#network={
#    ssid="Baker Wireless Network WiFi"
#    psk="xxxx"
#}
#network={
#    ssid="Rig2"
#    psk="xxxx"
#}
```

**Comment by Kdisimone** [comment]
Interfaces file:

```
root@devon1:~# cat /etc/network/interfaces
# interfaces(5) file used by ifup(8) and ifdown(8)
auto lo
iface lo inet loopback

auto usb0
iface usb0 inet static
    address 192.168.29.29
    netmask 255.255.255.0

auto wlan0
iface wlan0 inet dhcp
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
    # For WPA
    #wpa-ssid Emutex
    #wpa-psk passphrase
    # For WEP
    #wireless-essid Emutex
    #wireless-mode Managed
    #wireless-key s:password
# And the following 4 lines are for when using hostapd...
#auto wlan0
#iface wlan0 inet static
#    address 192.168.42.1
#    netmask 255.255.255.0

```

**Comment by Kdisimone** [comment]
Also tried both usb0 addresses during troubleshooting (192.168.2.15 and 192.168.29.29)...neither one caused any different behaviors from each other.  These were all wlan0 issues.

**Comment by scottleibrand** [comment]
Ok. My next troubleshooting step would be (will be if you don't beat me to it) to try putting those files on one of my rigs to see if they cause it to error out or not. If so, I'll work to narrow it down to a single minimal change that breaks/unbreaks it.

**Comment by Kdisimone** [comment]
FYI @scottleibrand A second person (totally separate from the first instance) has now reported the exact same issue.  

I'll try to get more info on what was going on when it happened

**Comment by Kdisimone** [comment]
@lydiaoxley  tagging you here

**Comment by Kdisimone** [comment]
And the first person's rig had the error reappear....a couple days ago.

**Comment by Kdisimone** [comment]
I'm going to move this to an issue in oref0

**Comment by danamlewis** [comment]
(Closing this for now because I believe it's being tracked in an issue (https://github.com/openaps/oref0/issues/648), please reopen if not the case.)

**Comment by Kdisimone** [comment]
Yup thanks!  Meant to close this awhile ago. 👍🏻

**Pull request closed without merging**
