### PR TITLE
Configuring and Learning to Use openaps Tools, General Formatting

### PR DESCRIPTION
**Pull request by channemann**
The bulk of this PR is in the "Configuring and Learning to Use openaps Tools" section. This is where we have been spending most of our time bringing new folks up to speed, so I thought it warranted a thorough makeover. It sits somewhere in between simply installing the openaps tools and actually building useful reports, aliases, and loops—more of an answer to the question “what the hell do `use` and `report` even do?” than to “what reports do I need?" I tried to take a conversational approach, similar to what actually happens when we're providing help on gitter or in person. I'd eventually like to take a similar approach to the preceding setup sections, explaining a bit more about what each step is doing.

I have also harmonized some of the formatting, moving towards a standardized use of markdown header levels in lieu of numbered lists and bolds with breaks. Not everything is fixed, but it's getting there.

Props to @danamlewis for all the review and comments on this one.

Also, because they were the latest guinea pigs, it would be great for @eszcloud and @msrcgm to take a look and see if walkthrough makes sense. To see it in GitBook form prior to merge, try https://channemann.gitbooks.io/openaps-docs/content/docs/Using-openaps-Tools/using.html

### CODE REVIEW

**Comment by channemann** [comment]
Also added @danamlewis's changes to the README (from https://github.com/openaps/docs/pull/7)

**Comment by danamlewis** [comment]
This is awesome. Thanks for all the great work @channemann, including pulling in my readme from #7.

+1/signoff by me for merging

@bewest, can you also give eyeballs/approve? or @scottleibrand, whoever gets online to review first.

**Comment by channemann** [comment]
Also pulled in @danamlewis's https://github.com/openaps/docs/pull/5/, listing watchdog as optional during setup.

**Comment by scottleibrand** [comment]
Edits and diff look good, as does the resulting book.  Further edits can be a new PR, so merging this now.

**Pull request merged**
