### PR TITLE
Update using.md

### PR DESCRIPTION
**Pull request by mikestebbins**
Explain addition of your password to the Bitbucket-provided origin URL to eliminate password prompts every time a '$ git push' is performed.

### CODE REVIEW

**Comment by scottleibrand** [comment]
Is it possible to set up an ssh key in Bitbucket like it is in github for passwordless pushes?

**Comment by oskarpearson** [comment]
https://confluence.atlassian.com/bitbucket/add-an-ssh-key-to-an-account-302811853.html has some info on how to set up ssh keys with BitBucket. Hope it helps!

**Comment by mikestebbins** [comment]
Thanks, Oskar.  I assume that the ssh key is preferred, so as not to expose my Bitbucket password out onto the internet?  
This is my first PR; what do I do next?  Close my PR, evaluate the information in the link and create a new PR with that info, if it seems appropriate to add to the documentation?  Thank you!

**Comment by scottleibrand** [comment]
You can leave the PR open and just update your branch with improved text
(probably recommending ssh keys, but mentioning that you can also do
passwords if you want), and it will automatically update the PR with your
changes.

-Scott

**Comment by mikestebbins** [comment]
Sounds good.  I'll try to take a look tonight and update the PR.  Thanks!

**Pull request closed without merging**
