### PR TITLE
Documenting Pebble IFTTT integration

### PR DESCRIPTION
**Pull request by logichammer**

### CODE REVIEW

**Comment by logichammer** [comment]
Pebble + IFTTT + OpenAPS == AWESOME!

**Comment by audiefile** [comment]
Much cleaner than my original gist! Nice pictures. I suggest checking you have the recipe set up correctly. You can test on the Maker Channel by looking under How To Trigger Events. If correctly setup, you should see a new temp target event on your Nightscout site after IFTTT says it successfully triggered. 

You can also add the DoButton app as a short cut. If you don’t have shortcuts already, press and hold either the up or down button and follow the prompts. If you have both shortcuts programmed and want to change one, go to menu > settings> quick launch and follow prompts.

**Comment by jasoncalabrese** [comment]
@audiefile ThisButton not DoButton, right?  I didn't see an official pebble app.

**Comment by logichammer** [comment]
I'll add this to my docs tomorrow night so @danamlewis / @scottleibrand if you want to wait until then, I will get it all added in...And will let you know when it it is good to go...

**Comment by audiefile** [comment]
Correct @jasoncalabrese ThisButton *not* DoButton for the pebble app

**Comment by danamlewis** [comment]
Added @audiefile 's notes to the page as well here: https://github.com/openaps/docs/commit/ec9c3c4a4718e2995c76b2283c5172187992300d

**Pull request merged**
