### PR TITLE
Updating basics

### PR DESCRIPTION
**Pull request by danamlewis**
-basic edits, adding links/other formatting
  -making the language more readable to an average user
  -built out the glossary based on preliminary terms
  -built out history page, note that it might be long for some tastes, but would like to prevent people from having to wade through OpenAPS.org 
  -Added a people list to the Resources page. Tagging @bewest @channemann @loudnate @amazaheri along with @scottleibrand  to grant permission to be included in the list. Others don't seem to be as public about their work, I pulled from who is live and tweeting, but we can add others as they finish and/or grant permission and/or ask to be included

### CODE REVIEW

**Comment by channemann** [comment]
Hey, thanks for finding my work in progress! I was thinking about pulling out those pictures in the hardware section, but maybe they're helpful. Is there an easy way to see all of these modifications in the gitbook version prior to the PR going through? I know I can do that with mine, but I think that's through my own gitbook account. Also, thanks for taking the time to update this!

**Comment by danamlewis** [comment]
I don't think the pictures in hardware add a ton, but I'm flexible either way.

I can turn it into a gitbook, but then you can't see them as tracked changes (I don't think, maybe @bewest can confirm). It might be easier to just see what I changed on top of your wip version if you want to see what I modified (this would do that: https://github.com/channemann/docs/compare/master...danamlewis:master), and otherwise look at the pages where I did a lot of work (history, resources) in preview mode?

**Comment by channemann** [comment]
Ah, that helps; thanks.

I'm with you, let's remove those hardware photos. The overview photo gives
a reasonable sense of what's used, even if it's not comprehensive. Plus the
links get you to the images anyway.

Also, you didn't like my "Getting Fancy" title? ;-)

On Tue, Sep 8, 2015 at 6:18 PM, Dana Lewis <notifications@github.com> wrote:

> I don't think the pictures in hardware add a ton, but I'm flexible either
> way.
>
> I can turn it into a gitbook, but then you can't see them as tracked
> changes (I don't think, maybe @bewest <https://github.com/bewest> can
> confirm). It might be easier to just see what I changed on top of your wip
> version if you want to see what I modified (this would do that:
> channemann@master...danamlewis:master
> <https://github.com/channemann/docs/compare/master...danamlewis:master>),
> and otherwise look at the pages where I did a lot of work (history,
> resources) in preview mode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaps/docs/pull/3#issuecomment-138745101>.
>



-- 
Chris Hannemann
chris.hannemann@gmail.com

**Comment by danamlewis** [comment]
Ok, removed the pics (I think they should still be baked into this overall PR). 

And nah :) I wanted to keep it a little more plain language for universal usability purposes ;) (trying to remember some of our counterparts may have a harder time translating slang and sarcasm into other languages :))

**Comment by channemann** [comment]
Yeah, I was just joshing. A lot of the stuff in there—especially near the
end—was just placeholders. Thanks for giving that glossary a go.

On Tue, Sep 8, 2015 at 6:26 PM, Dana Lewis <notifications@github.com> wrote:

> Ok, removed the pics (I think they should still be baked into this overall
> PR).
>
> And nah :) I wanted to keep it a little more plain language for universal
> usability purposes ;) (trying to remember some of our counterparts may have
> a harder time translating slang and sarcasm into other languages :))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaps/docs/pull/3#issuecomment-138746092>.
>



-- 
Chris Hannemann
chris.hannemann@gmail.com

**Comment by danamlewis** [comment]
Sure thing. Hoping we add to it as we go. As next steps am going to re-setup from scratch to validate the various setup instructions we have floating and will likely have some terms to go.

Can you confirm if you're ok being listed on the resources page, and if you'd prefer other links/references to yourself make that change or let me know?

**Comment by diabeticgonewild** [comment]
I have to make modifications to the hardware install steps for facilitating OpenAPS install. Some of the steps are erroneous when I executed the "headless install" from scratch.

Also, the need for transitioning from mobile WiFi access point to non-Internet based Raspberry Pi 2 access point. It's still work in progress and @bewest suggested ways to make the install process more seemless. The starting point for this install is here: https://github.com/diabeticgonewild/docs/blob/master/Setup/AccessPointEdimax.md

Eventually transitioning to a Docker may be more efficient than a "from scratch" install.

**Comment by diabeticgonewild** [comment]
I meant the improtance of a non-Internet access point on the Raspberry Pi 2 versus having to rely on a mobile connection.

**Comment by danamlewis** [comment]
@diabeticgonewild thanks, I'm also going to do an install from scratch in next week or so to check everything we've got documented so far. But for the sake of this PR, I didn't touch those other than any obvious typos I saw.

**Comment by channemann** [comment]
Just got to Resources (shows up at the bottom of the diff)—totally fine
with having my info there.

I've been working on a similar install-from-scratch from that gist doc I
sent out. Even if the final steps aren't used by all, the stuff up through
setting up openaps aliases should be reusable.

On Tue, Sep 8, 2015 at 6:36 PM, Monica <notifications@github.com> wrote:

> I have to make modifications to the hardware install steps for
> facilitating OpenAPS install. Some of the steps are erroneous when I
> executed the "headless install" from scratch.
>
> Also, the need for transitioning from mobile WiFi access point to
> non-Internet based Raspberry Pi 2 access point. It's still work in progress
> and @bewest <https://github.com/bewest> suggested ways to make the
> install process more seemless. The starting point for this install is here:
> https://github.com/diabeticgonewild/docs/blob/master/Setup/AccessPointEdimax.md
>
> Eventually transitioning to a Docker may be more efficient than a "from
> scratch" install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaps/docs/pull/3#issuecomment-138748832>.
>



-- 
Chris Hannemann
chris.hannemann@gmail.com

**Comment by diabeticgonewild** [comment]
@danamlewis you're welcome.

The problems that I know exist are:

1. SSHing in should be pi@raspberrypi.local (if my memory is correct!) NOT *.lan, and this needs to be changed. Changing the extension fixes the problem for SSHing in.

2. Being able to access Ext4 partitions consistently across Windows/Mac/Linux, with various but corresponding 3rd party open source software for Windows and Mac. Linux can access the Ext4 partition from within the operating system. So, basically a 3rd party softwares that are open source that work needs to be found and tested for Windows and Mac.

3. In Raspian, upon the first boot after running raspi-config etc/network/interfaces sometimes becomes rewritten, for some reason I have not figured out yet, but it does happen. So upon reboot, the previously properly configured file is nonexistent and so it the user cannot SSH in, the user has to take out the microSD card, check etc/network/interfaces to see if it had been reformatted. If so, change the file back to the settings that worked before for SSHing in. Additionally, rebooting and SSHing in a couple more times is advisable to make sure that the settings didn't reformat again. This is unlikely to be reformatted again, but it is worth it to check at least a couple of times to verify the problem doesn't occur again.

**Comment by danamlewis** [comment]
@channemann ok, thanks! And yes, I was going to use your gist, what's in here, and everything else (including notes below from @diabeticgonewild  - thanks!) as I went to compile the most full version I could make as I go :)

**Comment by channemann** [comment]
I ran into an issue near the end of the gist, so don't be surprised if you
get stuck :-) Still working it out, I'll update as I fix things.

On Tue, Sep 8, 2015 at 6:52 PM, Dana Lewis <notifications@github.com> wrote:

> @channemann <https://github.com/channemann> ok, thanks! And yes, I was
> going to use your gist, what's in here, and everything else (including
> notes below from @diabeticgonewild <https://github.com/diabeticgonewild>
> - thanks!) as I went to compile the most full version I could make as I go
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaps/docs/pull/3#issuecomment-138751042>.
>



-- 
Chris Hannemann
chris.hannemann@gmail.com

**Comment by danamlewis** [comment]
Realized we should re-emphasize baseline data collection (at least 30 days of cgm data and an a1c) prior to loop implementation to give people some pre vs post comparison data. added into initial setup as part of phase 0.

**Comment by bewest** [comment]
`.local` is correct.

**Comment by bewest** [comment]
Here are some random notes I came up with:

* https://gist.githubusercontent.com/bewest/d5f0fc68c0b9ac49c146/raw/32c42f51b9ee8baafe44d3248f7eb9dddca0f9d9/install_tools.sh
* https://gist.github.com/bewest/1d0ac7e5016fa47cde3a
* [about plugins](https://gist.github.com/bewest/710849c4a1deea59d5c3)
* [random debugging notes for when things go south](https://gist.github.com/bewest/a58a06dbab2d792a8642)
* yet-another-quick install https://gist.github.com/bewest/84f134f7b6d5375e2f04

Some of those scripts can be used like this `curl -s $gist | bash`, which will download the script in `$gist` from the internet and execute it.  This can be used to consolidate a lot of the manual steps, which don't really require any customization.

Just brain dump, getting some notes links into one place where there's some discussion happening. :-)  Thanks all.

**Comment by diabeticgonewild** [comment]
OK if we simplify the install process we should tell them that the command makes it less steps, plus what it does (so steps can be traced in case we make an error), and how it works (so people can understand conceptially and make recommendations for improvements).

Please understand that I am not against shortcuts. I like them and enjoy them, but if somebody is just issuing commands verbatim we are not doing ourselves or them a favor as we cannot correct errors or make improvements as effectively.

**Comment by diabeticgonewild** [comment]
Also, since there are multiple ways of collecting Dexcom data now, even through official Dexcom software or applications, should one of us make a short writeup or even make a YouTube video or something screen casting the upload, since those 30 prior days of data will be crucial for the OpenAPS project?

I really feel that some extra emphasis should be put and focused on this subject in the docs.

**Comment by danamlewis** [comment]
I'm of two minds re: a tutorial for data. One is sure, more documentation is better. The other is - being able to get 30 days of data should be a precursor of ability and computer skills to proceed with the rest of the project. That, or the ability to find someone to ask/help you, and that's not an openaps specific task. (Maybe this changes if we have dozens of Qs about that, but maybe for now it's a precursor.)

**Comment by diabeticgonewild** [comment]
I am not concerned about computer skills regarding the data collection at all. I just want to make sure that the data is properly collected: such as in a CSV or a TAB Delimited file. Whatever is decided upon for the 30 days "required" prior to OpenAPS implementation needs to be "streamlined" and agreed upon regarding formatting and even how it is to be submitted to X, Y, and Z parties right from the start, or all of these efforts that we are working towards could be futile which would be devastating.

**Comment by danamlewis** [comment]
Good points. Once we define standards for data collection that we're recommending as part of the process, we'll definitely document them.

**Comment by channemann** [comment]
May I suggest one way to get that data _and_ practice using openaps—generating a report using the `glucose` command (for dexcom devices) or whatever the equivalent is the Medtronic CGM (not sure if it's `read_glucose_data` or `read_current_glucose_pages`. It may not be CSV data, but it gets the data dump taken care of and introduces the user to many steps in the `openaps` chain.

**Pull request merged**
