### PR TITLE
oref0-reset-git cron example

### PR DESCRIPTION
**Pull request by Spazholio**

### CODE REVIEW

**Comment by scottleibrand** [comment]
You should merge master/dev to your branch to clean up these duplicate commits.

**Comment by scottleibrand** [comment]
New stuff looks good: will merge after you do that.

**Comment by Spazholio** [comment]
Happy to do it, once I understand what you mean.   Am I out of sync somewhere?  If I am, how to best check on that/fix it?

**Comment by scottleibrand** [comment]
https://github.com/Spazholio/docs/pull/1

**Pull request merged**
