### PR TITLE
Adding warnings about Password-less login

### PR DESCRIPTION
**Pull request by dougtakeuti**
In my opinion we shouldn't explain how things could go wrong. Sleep-deprived foreigners like me could easily interpret that the opposite way :)

### CODE REVIEW

**Comment by scottleibrand** [comment]
I don't see any passwordless login stuff, just the .git sudo fix from a few weeks ago.

**Comment by dougtakeuti** [comment]
Two possibilities:
1) I've done something wrong submitting the PR
2) I'm so clueless that I don't get what the issue is
Feel free to ask @Spazholio to do it. However, I'll like to overcome this
learning curve so I could contribute somehow. Could you please paste a
fragment of what you see so I can figure this out?

2016-05-20 23:11 GMT-03:00 Scott Leibrand <notifications@github.com>:

**Comment by scottleibrand** [comment]
https://github.com/openaps/docs/pull/179/files

**Comment by dougtakeuti** [comment]
Sorry, wrong PR. Let me try to fix this.

2016-05-20 23:43 GMT-03:00 Scott Leibrand <notifications@github.com>:

**Pull request closed without merging**
