### PR TITLE
understand before doing

### PR DESCRIPTION
**Pull request by bewest**
Move the openaps mechanics/introduction ahead of the walkthrough.
According to @ddaniels1, this was useful.

### CODE REVIEW

**Comment by bewest** [comment]
* http://openaps.readthedocs.io/en/wip-understand-before-doing/
---------------------------------------------

This starts to pull in lot of advice from:


* https://github.com/openaps/docs/issues/129
* https://github.com/openaps/docs/issues/132
* https://github.com/openaps/docs/issues/136

**Comment by scottleibrand** [comment]
I like this.  I would title the phases something like: Phase 1: Monitoring and Visualization; Phase 2: Creating an Open Loop; Phase 3: Automated Control

👍 to merge this to dev.  @danamlewis should take a look over it and decide when to merge.

**Comment by dm61** [comment]
@danamlewis and @scottleibrand, I vote to merge this WIP version to dev at least, if not directly to master. The order of walkthrough Phase1/2 sections in the current master/dev is very confusing for new people, This WIP version fixes that outstanding problem. Furthermore, it already includes lots of Ben's new work (e.g. templates and helpers), which simplifies the process, without necessarily removing the need to understand the system details.

**Comment by danamlewis** [comment]
If someone will fix the merge conflicts, I'll give it a +1 to get merged. Then will suggest @japrobo do any further edits on flow from here related to the NS setup section so he's not duplicating efforts.

**Comment by bewest** [comment]
Conflicts fixed.

**Comment by japrobo** [comment]
I like it.  We found these documents helpful.

**Pull request merged**
