### PR TITLE
Dev: edits in Using-oref0-tools.md

### PR DESCRIPTION
**Pull request by dm61**
Expanded using-oref0-tools section and made various edits throughout the section; updated the enact subsection based on Scott's comment.

### CODE REVIEW

**Comment by scottleibrand** [comment]
Excellent work!  My only major comment would be around providing a copy-and-pastable command for the enact/enacted.json report.  We very intentionally left that out of the docs, so that anyone blindly copying and pasting things couldn't get a fully working loop without really reading and understanding what they were doing.  So it would probably be best to remove those actual commands (while still explaining the theory behind them, as you've done so well) to leave that final step as an "exercise for the reader".

**Comment by danamlewis** [comment]
Ditto, for a +1 following that revision. Thanks for adding good
explanations to this section!

On Saturday, January 9, 2016, Scott Leibrand <notifications@github.com>
wrote:

> Excellent work! My only major comment would be around providing a
> copy-and-pastable command for the enact/enacted.json report. We very
> intentionally left that out of the docs, so that anyone blindly copying and
> pasting things couldn't get a fully working loop without really reading and
> understanding what they were doing. So it would probably be best to remove
> those actual commands (while still explaining the theory behind them, as
> you've done so well) to leave that final step as an "exercise for the
> reader".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaps/docs/pull/75#issuecomment-170315846>.
>


-- 
Dana Lewis | http://diyps.org | @DanaMLewis
<http://www.twitter.com/danamlewis> | http://www.linkedin.com/in/danalewis
"Doing something for someone else is more important than anything you would
do for yourself."

**Comment by dm61** [comment]
Removed commands from the enact subsection, left the hints as questions to think about. What do you think?

**Comment by scottleibrand** [comment]
Looks good, thanks!  Merging to dev.

**Pull request merged**
