### PR TITLE
Papertrail troubleshooting

### PR DESCRIPTION
**Pull request by Kdisimone**
added screenshots of error messsages

expanded section to include NOT error messages

### CODE REVIEW

**Comment by Kdisimone** [comment]
More screenshots to be uploaded...hold on

**Comment by Kdisimone** [comment]
Ok, I think I got all the kinks worked out and files uploaded @danamlewis

**Comment by Kdisimone** [comment]
@danamlewis. Hold off on this for a bit. I'm going to change a few things when I have a minute and get back to home. Thanks

**Comment by Kdisimone** [comment]
@danamlewis Ok...fixed my issues.  Thanks

**Comment by danamlewis** [comment]
This is great. @Kdisimone can you also think about where to stick the troubleshooting/normal error message section around "troubleshooting the setup" page? Would be great to have there, too :D

**Pull request merged**
