### PR TITLE
Update quick-packages.sh to support WSL

### PR DESCRIPTION
**Pull request by McHoffi**
nodejs-legacy gave an error, just nodejs worked on WSL

### CODE REVIEW

**Comment by McHoffi** [comment]
Sorry, I don´t know how to code, but for me it worked then like this. Or shall I make a PR for the wiki in the section where common problems are described?

**Comment by scottleibrand** [comment]
Yeah, if there's no one using WSL who can help set up a test for when we're on WSL and should use `nodejs` (vs. being on Debian and using `nodejs-legacy`) it might be best to just note it in the docs, with a reference to this issue for anyone who later wants to fix the code.

**Comment by sethgagnon** [comment]
I use WSL and could test. Is there a branch out there I should pull from to try to run the following command from:

sudo curl -s https://raw.githubusercontent.com/openaps/docs/master/scripts/quick-packages.sh | bash -

**Comment by scottleibrand** [comment]
What we need here is for someone to develop a way for the script to detect whether you’re on WSL or Debian.

**Comment by sethgagnon** [comment]
#!/bin/bash
# Running under WSL (Windows Subsystem for Linux)?
if cat /proc/version | grep Microsoft; then
    WSL_running=true
else
    WSL_running=false
fi

# TODO: remove the `-o Acquire::ForceIPv4=true` once Debian's mirrors work reliably over IPv6
apt-get -o Acquire::ForceIPv4=true install -y sudo
sudo apt-get -o Acquire::ForceIPv4=true update && sudo apt-get -o Acquire::ForceIPv4=true -y upgrade
if [[ $WSL_running == true ]]; then
	#Run just nodejs
	sudo apt-get -o Acquire::ForceIPv4=true install -y git python python-dev software-properties-common python-numpy python-pip nodejs npm watchdog strace tcpdump screen acpid vim locate jq lm-sensors bc && \
else
	#Run just node-legacy
	sudo apt-get -o Acquire::ForceIPv4=true install -y git python python-dev software-properties-common python-numpy python-pip node-legacy npm watchdog strace tcpdump screen acpid vim locate jq lm-sensors bc && \
sudo pip install -U openaps && \
sudo pip install -U openaps-contrib && \
sudo openaps-install-udev-rules && \
sudo activate-global-python-argcomplete && \
sudo npm install -g json oref0 && \
echo openaps installed && \
openaps --version

**Comment by sethgagnon** [comment]
for quick-packages.sh:

`#!/bin/bash
# Running under WSL (Windows Subsystem for Linux)?
if cat /proc/version | grep Microsoft; then
    WSL_running=true
else
    WSL_running=false
fi

# TODO: remove the `-o Acquire::ForceIPv4=true` once Debian's mirrors work reliably over IPv6
apt-get -o Acquire::ForceIPv4=true install -y sudo
sudo apt-get -o Acquire::ForceIPv4=true update && sudo apt-get -o Acquire::ForceIPv4=true -y upgrade
if [[ $WSL_running == true ]]; then
	#Run just nodejs
	sudo apt-get -o Acquire::ForceIPv4=true install -y git python python-dev software-properties-common python-numpy python-pip nodejs npm watchdog strace tcpdump screen acpid vim locate jq lm-sensors bc && \
else
	#Run just node-legacy
	sudo apt-get -o Acquire::ForceIPv4=true install -y git python python-dev software-properties-common python-numpy python-pip node-legacy npm watchdog strace tcpdump screen acpid vim locate jq lm-sensors bc && \
sudo pip install -U openaps && \
sudo pip install -U openaps-contrib && \
sudo openaps-install-udev-rules && \
sudo activate-global-python-argcomplete && \
sudo npm install -g json oref0 && \
echo openaps installed && \
openaps --version`

I was able to test this on WSL, but maybe someone else can try it on Debian to confirm it works from that system?

**Comment by scottleibrand** [comment]
Looks good:
```
# if cat /proc/version | grep Microsoft; then WSL_running=true; else WSL_running=false; fi; echo $WSL_running
false
```

**Comment by sethgagnon** [comment]
Great, all good then or shall I submit a PR?

**Comment by scottleibrand** [comment]
Yeah, we need a PR that does that check and then conditionally runs either the current line or the modified one depending on the value of `$WSL_running`.  Thanks!

**Comment by sethgagnon** [comment]
https://github.com/openaps/docs/pull/1378

**Comment by danamlewis** [comment]
(Closing in favor of #1378 )

**Pull request closed without merging**
