### PR TITLE
Update loops-in-progress.md

### PR DESCRIPTION
**Pull request by dirkgastaldo**
Added me back. I used to be on this list, but somehow was removed. Do you know if someone cleanses/edits this list and removes names?

### CODE REVIEW

**Comment by scottleibrand** [comment]
Looks like the loops-in-progress.md file was copied to a new location, and folks who added themselves in the old location didn't get copied over to the new location when we merged the new dev docs to master.  I just did so manually, so both copies are now in sync.  We should now delete the one that's not used, but I haven't yet tried to figure out which that is.

**Comment by scottleibrand** [comment]
The two files are https://github.com/openaps/docs/blob/master/docs/docs/walkthrough/phase-0/loops-in-progress.md and https://github.com/openaps/docs/blob/master/docs/docs/While%20You%20Wait%20For%20Gear/loops-in-progress.md

**Comment by danamlewis** [comment]
@scottleibrand https://github.com/openaps/docs/blob/master/docs/docs/walkthrough/phase-0/loops-in-progress.md is the one to be deleted (see phase 0 in the URL? that's old style nav)

**Comment by danamlewis** [comment]
Deleted, resolved, closing.

**Pull request closed without merging**
