### PR TITLE
This is the fast stuff I can add

### PR DESCRIPTION
**Pull request by logichammer**
Marked a few questions with DL so you could find them quickly.

I have more I need to do with my setup (add in push notifications / understand how and why it has certain recommendations so I will have more to add later).

### CODE REVIEW

**Comment by scottleibrand** [comment]
there is a read_current_basal_profile or some such that reads whichever pattern is active. That's the one we want.

clock.json is used as the "now" for IOB calculations.

**Comment by logichammer** [comment]
Perfect...will update docs (and my own install!) with this!

**Comment by logichammer** [comment]
Updated and ready to merge into master if you like what you see.

**Comment by danamlewis** [comment]
Looks good, thanks @logichammer

**Pull request merged**
