### PR TITLE
Update monitoring-OpenAPS.md

### PR DESCRIPTION
**Pull request by audiefile**
Add note for reason offline webpage may not load and fix for it.

### CODE REVIEW

**Comment by audiefile** [comment]
The offline webpage does not appear at all if that line is not in crontab. 

I'm on dev right now. Without that line I would get errors trying to access the site in browser, with the site will load. It will work with dev code but I'm not sure that I have the new style cron jobs.

**Comment by scottleibrand** [comment]
Have you re-run oref0-setup since the 0.7.0-dev refactor?  If so, your crontab will just have a few lines, running oref0-cron-every-minute, oref0-cron-every-15min, oref0-cron-nightly, and oref0-cron-post-reboot. The latter has:

bin/oref0-cron-post-reboot.sh:    flask run -p 80 --host=0.0.0.0 | tee -a /var/log/openaps/flask.log

**Comment by audiefile** [comment]
I did re-run the interactive setup last week after pulling what was then the latest dev branch. However, I still have a 'old' style crontab with a dozen or so lines.

**Comment by scottleibrand** [comment]
Do you remember whether you deleted and replaced your crontab when you did oref0-setup?

**Comment by audiefile** [comment]
I did not manually delete it and the script didn't ask about cron setup.

**Comment by scottleibrand** [comment]
Sounds like oref0-setup didn't complete successfully then.  It should always prompt to replace crontab at the end.  I'd suggest re-running it.

**Comment by audiefile** [comment]
I did. This time it did ask about cron but it's still the old style

**Comment by scottleibrand** [comment]
If you don't delete the old crontab, it'll keep the old lines and add the new ones as well.  You'll want to say Yes to deleting the old crontab and let it recreate it.

**Comment by audiefile** [comment]
I did remove the existing crontab.

**Comment by scottleibrand** [comment]
If you're getting old-style cron entries re-added after removing the existing crontab, then you haven't successfully installed the latest oref0 dev before running oref0-setup.  The dev oref0-setup code is now this: https://github.com/openaps/oref0/blob/dev/bin/oref0-setup.sh#L1359-L1396

**Comment by audiefile** [comment]
The new style crontab works

**Comment by scottleibrand** [comment]
Cool.  Do you know what the problem was that prevented you from getting a new-style crontab earlier? 
Should we revise this PR to mention that as a better fix?  Or leave the docs as-is?

**Pull request merged**
