### PR TITLE
Changes to multiple steps esp for Windows OS

### PR DESCRIPTION
**Pull request by jcorbett80**

### CODE REVIEW

**Comment by jcorbett80** [comment]
For this part I worked on so far. Do I need to do anything goes else or
were the things suggested by others in reply already taken care of?

James

**Comment by danamlewis** [comment]
@jcorbett80 I just merged all the approved changes in, so this PR is closed. If you have more edits, you can open a new PR (you may want to pull a fresh copy of master again before you start so you get all the fresh updates that have come along since then).

**Comment by scottleibrand** [comment]
You can also take a look at https://github.com/openaps/docs/pull/712/files to see the resulting changes from my edits, or https://github.com/openaps/docs/pull/712/commits to see the specific commits.

**Comment by jcorbett80** [comment]
Thank you. I do have more and will get those done as soon as I can.

James

**Pull request merged**
