### PR TITLE
updating Workflow -> Apple Shortcuts info

### PR DESCRIPTION
**Pull request by Cfomodz**
Phone triggers from Workflow (now Apple Shortcuts) needed updated due to name change and functionality reduction - removing IFTTT triggers being a direct option. A workaround is available and is explained / linked to original source. This is my first proposed file change besides doing a PR to add my name to the list of rigs, so please let me know if I am doing anything wrong via Gitter @Cfomodz and I will take care of it. Additionally, I will add photos to this shortly.

### CODE REVIEW

**Comment by danamlewis** [comment]
@Cfomodz (will wait to review further until you add the new photos, rather than merging as-is). Let me know if you need any help subbing in the new photos.

**Comment by Cfomodz** [comment]
@danamlewis I would love some help with that. When trying to upload files I was faced with a notice saying I couldn't upload files.

"Uploads are disabled.
File uploads require push access to this repository."

Do I need to upload them somewhere else and just img src them in?

**Comment by danamlewis** [comment]
@Cfomodz no, what you should do is upload the images (you can do it as a batch) to your /Images folder in your fork (this one is patch-8, so make sure you're uploading in that branch of your fork). Here's some more visuals that may help: https://openaps.readthedocs.io/en/latest/docs/Resources/my-first-pr.html#advanced-tips-for-adding-multiple-images-to-documentation

Once you get the images uploaded, you can then add the references to the Shortcuts section to display them. Don't worry if you can't get the images formatted correctly to display; just get them to where they should be in the section, and referring to the correct image, and I can help format correctly at the end when I review the PR!

**Comment by Cfomodz** [comment]
Got it. I will get to work on that - I'll need to take them all and add arrows and highlighting and stuff, but I will @ you when I get it done and am ready to go!

**Comment by danamlewis** [comment]
just a nudge @Cfomodz :) for images

**Comment by danamlewis** [comment]
Resolved via https://github.com/openaps/docs/pull/1495

**Pull request closed without merging**
