### PR TITLE
Spring cleanup and restructure - dana-dev to dev

### PR DESCRIPTION
**Pull request by danamlewis**
**What this includes:**

- Work to create the big restructure we've been talking about needing, which evolves the "phase" approach to help people learn more about the algorithm and process and less about having to jump through coding hoops. This will be the starting place to filling in even more support for easing the messy bits we can consolidate, and focus on more steps to learning (like how many days to spend testing X, and how to go about testing and validating understanding of X). 

**Also includes:**

- @bewest work to create a Read The Docs implementation, which will be linked from the ReadMe
- @bewest work on the guide to the openaps tools. Ditto for making major edits and contributions after this is merged to dev. 

**After this is merged:**
Asking open PRs left (https://github.com/openaps/docs/pull/91; https://github.com/openaps/docs/pull/92; https://github.com/openaps/docs/pull/93; https://github.com/openaps/docs/pull/94; https://github.com/openaps/docs/pull/95 ) to re-review their work and see if they need to update anything to re-target dev *after* this big one is merged.

Feel free to make any notes here in the thread about things you'd like to see adjusted, but please specify whether they're adjustments that can be made after the merge to dev so we can track those things but not necessarily hold up the merge. Ideally, this is better than dev as-is and we can make more changes in dev before submitting as a PR to master in another week or two. Give it a thumbs up when you're ready to support merging to dev.

### CODE REVIEW

**Comment by jmatheson** [comment]
#91 is ready to go

**Comment by danamlewis** [comment]
For easier view of what the new structure looks like, you can look at the
Read The Docs rendering of this branch here:
http://openaps.readthedocs.org/en/dana-dev/

On Wednesday, March 30, 2016, CrushingT1D <notifications@github.com> wrote:

> #91 <https://github.com/openaps/docs/pull/91> is ready to go
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/openaps/docs/pull/114#issuecomment-203521764>
>


-- 
Dana Lewis | http://www.twitter.com/danamlewis |
http://www.linkedin.com/in/danalewis
"Doing something for someone else is more important than anything you would
do for yourself."

**Comment by scottleibrand** [comment]
:+1: to merge to dev.  This is definitely better than what we have now.

**Comment by bewest** [comment]
:+1:

**Pull request merged**
