### PR TITLE
Table update: third time's the charm

### PR DESCRIPTION
**Pull request by inventor96**
My third and hopefully last attempt at fixing the table layout.

Last try was #1589.

### CODE REVIEW

**Comment by danamlewis** [comment]
Screen Shot 2023-02-15 at 11 56 21 AM

Looks better than before, but still not our ideal table. (https://openaps--1590.org.readthedocs.build/en/1590/docs/Gear%20Up/edison.html#soldering to preview)

**Comment by inventor96** [comment]
:man_facepalming: This is brutal. Thanks for the preview link; that will help me make it look decent without going after tons of PRs!

**Comment by inventor96** [comment]
@danamlewis Based on that preview link, it looks ready to me. We'll call it attempt 3.5. :laughing:

**Comment by danamlewis** [comment]
Woohoo! Looks great now. thanks for persevering, @inventor96 , and sorry it's such a hassle.

**Pull request merged**
