### PR TITLE
Autotune tune insulin description

### PR DESCRIPTION
**Pull request by jpcunningh**

### CODE REVIEW

**Comment by jpcunningh** [comment]
@scottleibrand, please check the additional words to describe how useCustomPeakTime affects autotune now.

**Comment by jpcunningh** [comment]
With that in mind, does it make sense to add some explanatory comment about
how it pulls in the dia and peak from the pumpprofile unless
--tune-insulin-curve is used or useCustomPeak is set?

**Comment by scottleibrand** [comment]
Without useCustomPeakTime, DIA comes from the pump, but peakTime comes from the defaults for the curve selected in preferences.json.

**Comment by jpcunningh** [comment]
How does that look?

**Pull request merged**
