### PR TITLE
Update my-first-pr.md

### PR DESCRIPTION
**Pull request by marionbarker**
Fixed a typo

### CODE REVIEW

**Comment by marionbarker** [comment]
This is my hello world for doc update.  Was the typo there just to see if we are paying attention?

**Comment by scottleibrand** [comment]
Heh, good catch. Looks like you closed the PR and deleted your branch with the fix before we got a chance to merge it, though.

**Comment by marionbarker** [comment]
Oops - I was at the point in the doc where it says

 

“PS, your fork will still be sitting on your own personal github account. You can delete it if you are done with it. In the

future, be sure to pull a fresh copy from github.com/openaps/docs before making new edits.”

 

But I guess I was not in my personal location when I deleted it. I will try again and add a “go to your personal github first before deleting” edit.  I saw some comments in issues about editing docs to master instead of dev.  I will use dev until told otherwise.

 

Since I have your attention, my husband has several pi in his drawer leftover from a project (had to step up to banana pi for that project, so the raspberry ones are sitting around). It is at wheezy so I thought I’d just give it a try.  I get an error when I do the 

curl -s https://raw.githubusercontent.com/openaps/docs/master/scripts/quick-packages.sh | bash -

so my next plan is to get a new SD card configured for Raspbian 8 Jessie or newer.  If there’s something else I’m missing, please reply.  I know I need to get the Jessie anyway.

 

It gets almost to the end, then the first few lines of errors are:

Installing bash completion script /etc/bash_completion.d/python-argcomplete.sh

npm http GET https://registry.npmjs.org/json

npm http GET https://registry.npmjs.org/oref0

 

npm ERR! Error: failed to fetch from registry: oref0

npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12

npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)

npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)

npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)

npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)

npm ERR!     at Request.emit (events.js:88:20)

npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)

npm ERR!     at ClientRequest.g (events.js:156:14)

npm ERR!     at ClientRequest.emit (events.js:67:17)

npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)

 

Thanks much for making all this available.  Having fun.  Hoping to have this understood and ready to go when the Omnipod gets cracked.

 

Regards - Marion

**Comment by scottleibrand** [comment]
Sounds like you're moving too that doc too fast.  You can't delete your branch until after we merge the PR.  Perhaps we need another PR to make that more clear.  :-)

Looks like your Pi has the wrong version of nodejs.  I would ask in Gitter about how to fix that.

**Pull request closed without merging**
