### PR TITLE
Create Papertrail service

### PR DESCRIPTION
**Pull request by Kdisimone**
Instructions for setting up papertrailapp service for remote viewing of openaps loop logs

### CODE REVIEW

**Comment by danamlewis** [comment]
Woot! I'd suggest storing this in Phase 1 for visualization/monitoring? (So just move to phase 1). And, add .md to the title of the file and that'll enable your great markdown formatting to work :)

**Comment by Kdisimone** [comment]
Great idea...will do.  I wondered why the preview wasn't working. 👍

**Comment by Kdisimone** [comment]
Ok, should be all moved over to Phase 1.  Thanks

**Comment by Kdisimone** [comment]
FIXED!  Yeah!

**Pull request merged**
